excel:
  name: 'futureloan_web_test_pytest_version.xlsx'

implicitly_wait: 20

host: 'http://120.78.128.25:8765'

fmt: '%Y-%m-%d-%H-%M-%S'

tester:
  mobile_phone: '18584086762'
  pwd: 'yey1201abc'

administrator:
  mobile_phone: '18581512456'
  pwd: 'yey1201abc'

investor:
  mobile_phone: '15883308876'
  pwd: 'yey1201abc'

investor_id: 7961
tester_id: 7953
administrator_id: 7954